In [4]:
# Import libraries
%matplotlib inline
from sklearn import datasets
import matplotlib.pyplot as plt
import numpy as np

training_data = [
    np.array([0,0,1]),
    np.array([0,1,1]),
    np.array([1,0,1]),
    np.array([1,1,1]),
]

target = [0,1,1,0]

w = np.random.rand(3) # Initializing weights randomly.
errors = []
eta = 0.2 # Learning rate
n = 100 # Number of iterations

In [118]:
class ANN:
    ''' This is an artificial neural network'''
    def __init__(self, numLayers, Input, hiddenNeuronList=[]):
        self.numLayers = numLayers
        self.numHiddenLayers = numLayers - 2
        
        if not len(hiddenNeuronList):
            self.hiddenNeuronList = [len(Input)]*self.numHiddenLayers ## Should be changed later to something more general
        else:
            self.hiddenNeuronList = hiddenNeuronList
            
        self.construct_network(Input)
        self.connect_layers()
            
    def construct_network(self,Input):
        # Input layer Stuff
        self.input_layer = input_layer(Input)
        
        # Create Hidden Layers
        self.hidden_layers = [hidden_layer(self.hiddenNeuronList[i]) for i in range(self.numHiddenLayers)]
        
        # Create output layer
        self.output_layer = output_layer(1)

    def connect_layers(self):
        '''Connect layers'''
        # Input layer
        self.hidden_layers[0].connect_layer(self.input_layer)
        # Hidden layers
        for n in range(self.numHiddenLayers-1):
            self.hidden_layers[n+1].connect_layer(self.hidden_layers[n])
        # Output layer
        self.output_layer.connect_layer(self.hidden_layers[-1])
        
class neuron_layer:
    ''' This is a neural network layer'''

    def __init__(self, N):
        self.N = N
        self.neurons = [neuron() for i in range(N)]

    def connect_layer(self, prev_layer):
        self.prev_layer = prev_layer
        prev_layer.set_next_layer(self)
        numEdges = prev_layer.N * self.N
        for n in self.neurons:
            n.initialize_weights(prev_layer.N)
        
    def compute_layer(self):
        y = []
        for n in self.neurons:
            y.append(n.compute(self.prev_layer.output))
        self.output = y
        return self.output
    
    def backpropagate():
        pass

class input_layer(neuron_layer):
    ''' This is the input layer'''

    def __init__(self, Input):
        self.N = len(Input)
        self.output = self.compute_layer(Input)
    
    def compute_layer(self,x):
        return x
    
    def set_next_layer(self, next_layer):
        self.next_layer = next_layer

class hidden_layer(neuron_layer):
    def set_next_layer(self, next_layer):
        self.next_layer = next_layer
            
class output_layer(neuron_layer):
    pass

class neuron:
    '''Units inside a layer'''
    
    def __init__(self):
        pass
    
    def initialize_weights(self, numInputs):
        self.w = np.random.uniform(-1,1,numInputs)
        #self.w = np.zeros(numInputs) # Just for kicks
    def sigmoid(x):
        ''' This is our activation function. '''    
        return 1/(1+np.exp(-x))
    def compute(self,x):
        return sigmoid(np.dot(self.w,x))  

In [105]:
hl = neuron_layer(2)
ol = neuron_layer(1)
il = input_layer([2,1,1])

ol.connect_layer(hl)
hl.connect_layer(il)
 
x = np.array([1,1])
    
y = il.compute_layer(x)
y1 = hl.compute_layer()

AttributeError: 'neuron_layer' object has no attribute 'set_next_layer'

In [119]:
x = [1,1,1,1,1,1,1]

In [124]:
nn1 = ANN(5, x, [2,3,4])

In [125]:
nn1.hidden_layers[0].next_layer

In [122]:
nn1.output_layer.neurons[0].w

array([ 0.76774596,  0.8413687 ,  0.01308038,  0.54138358,  0.24054085,
        0.80310769,  0.97148677])

In [11]:
ol.w

array([-0.40810821, -0.70716352])

In [12]:
hl.w

array([-0.09764534, -0.90863829, -0.10203447,  0.84799126])